[package]
name = "GameJam2021"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
euclid = "0.22.6"
glam = "0.20.0"
legion = { version = "0.4.0", features = ["wasm-bindgen"], default-features = false }
macroquad = "0.3.10"
nalgebra = "0.29.0"
wfc = { version = "0.10.4", features = ["js"] }

[features]
