#![allow(dead_code)]
// Autogenerated using: cargo run --example make-spritesheet
use macroquad::math::XY;

pub struct FrameRect {
    pub xy: XY<u32>,
    pub uv: XY<f32>,
    pub topleft_xy: XY<u32>,
    pub topleft_uv: XY<f32>,
}

pub const SPRITESHEET_PNG_BYTES: &[u8] = include_bytes!("spritesheet.png");

pub const BEE_FLYING_FRAME_SIZE: XY<u32> = XY {
    x: 125u32,
    y: 128u32,
};
pub const BEE_FLYING_FRAME_UV: XY<f32> = XY {
    x: 0.33333334f32,
    y: 1f32,
};
pub const BEE_FLYING_SPRITE_Y_OFFSET: u32 = 0u32;
pub const BEE_FLYING_FRAMES: [FrameRect; 3] = [
    FrameRect {
        xy: XY { x: 0u32, y: 0u32 },
        uv: XY { x: 0f32, y: 0f32 },
        topleft_xy: XY {
            x: 125u32,
            y: 128u32,
        },
        topleft_uv: XY {
            x: 0.33333334f32,
            y: 1f32,
        },
    },
    FrameRect {
        xy: XY { x: 125u32, y: 0u32 },
        uv: XY {
            x: 0.33333334f32,
            y: 0f32,
        },
        topleft_xy: XY {
            x: 250u32,
            y: 128u32,
        },
        topleft_uv: XY {
            x: 0.6666667f32,
            y: 1f32,
        },
    },
    FrameRect {
        xy: XY { x: 250u32, y: 0u32 },
        uv: XY {
            x: 0.6666667f32,
            y: 0f32,
        },
        topleft_xy: XY {
            x: 375u32,
            y: 128u32,
        },
        topleft_uv: XY { x: 1f32, y: 1f32 },
    },
];
